### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by TamasBarta** [KryDos/todoist-linux#10]
Hi, 
can you please provide instructions for building it ourselves? I'm not familiar with this node thingy, but want to try this on Arch (so DEB and RPM is not ideal). Thanks!

**Comment by KryDos** [comment]
hey @TamasBarta, sure, I'll write instructions in README.md to help contributors. I hope it will be useful for you as well. 

Thanks a lot for your interest! Arch's  PKGBUILD will be super useful .
