### ISSUE TITLE
Config file not created

### ISSUE THREAD

**Issue by NicoWeio** [KryDos/todoist-linux#104]
I'm using *Linux Mint 20*, and I installed this application using the latest *deb*. Everything works fine, but I cannot configure the shortcuts without a configuration file. In `~/.config/` there is no `.todoist-linux.json` as described in the *README*. There is a *Todoist* directory, but it doesn't contain any *json* files. 
One hint might me the following: `echo $XDG_CONFIG_HOME` gives no output.

**Comment by KryDos** [comment]
hey @NicoWeio, 
Thanks for the report!

The app should fallback to `~/.config` if there is no `$XDG_CONFIG_HOME` env variable defined. Could you run the app from your terminal and see if any permission related errors are showing up?

**Comment by NicoWeio** [comment]
Already did that, although not on the very first start. I see absolutely no output there.

**Comment by NicoWeio** [comment]
Oops, my fault. I don't know what exactly went wrong, but it seems like I just overlooked the file. Will close once its functionality is confirmed.

**Comment by KryDos** [comment]
whew

**Comment by nsheff** [comment]
I'm having a similar issue; just installed in ubuntu 19.04 and there is no config file. Runing the app from the command line shows no permission errors:

```
todoist
SNAP env is defined, updater is disabled
```

There is no todoist folder or .todoist... file in `~/.config`. F

`echo $XDG_CONFIG_HOME` is empty.
