### ISSUE TITLE
I can't uninstall it on Kubuntu 20.04

### ISSUE THREAD

**Issue by jayaherkar** [KryDos/todoist-linux#105]
I ran sudo apt remove ./TodoistPackage but still the app persists in the system. Anyone facing similar issue?

**Comment by KryDos** [comment]
hey @jayaherkar, thanks for the report. 

Do you see any info/warning/error messages when you run `apt remove` command?

**Comment by jayaherkar** [comment]
Nope! I finally manually removed Todoist files from /opt and also removed desktop entry file so it's good now but I didn't got any error while running `apt remove` command

**Comment by KryDos** [comment]
Strange. Glad you were able to remove it manually. 

I'll keep the issue open until it's confirmed that `apt` is able to remove the app. Thanks again for the report

**Comment by jayaherkar** [comment]
I was able to remove it manually but I can't install it now.
![Screenshot_20200908_211403](https://user-images.githubusercontent.com/54982718/92498421-3aed7980-f218-11ea-8a94-2069e7eceac4.png)

**Comment by jayaherkar** [comment]
You got any idea why this issue happened in the first place? Also after removing files from `/opt` and removing desktop files still it's saying Todoist is installed. Please let me know how to solve this.

**Comment by jayaherkar** [comment]
I can still see Todoist in apt installed package list. I used this command `sudo apt list --installed`
![Screenshot_20200908_211901](https://user-images.githubusercontent.com/54982718/92498971-ef879b00-f218-11ea-8169-62623cdf0093.png)

**Comment by KryDos** [comment]
Ok so the app is removed manually and apt doesn't know about it and still thinks the app is installed. APT has its own DB so it make sense that the DB doesn't know about the manual remove. 

Can you try to delete it with `apt remove todoist`?

**Comment by jayaherkar** [comment]
Yeah! It's working that way. Thanks. I removed that and installed again. No Problems now :)

**Comment by KryDos** [comment]
Perfect!
