### ISSUE TITLE
Google signing not working 

### ISSUE THREAD

**Issue by Rahul7f** [KryDos/todoist-linux#107]
![image](https://user-images.githubusercontent.com/51960262/92554824-e08a0280-f283-11ea-9591-967b8ad5b360.png)

**Comment by KryDos** [comment]
Interesting. Thanks for the report @Rahul7f, 
Didn't you try Ctrl+R to refresh the page as it stated in the message? I'm not sure if Ctrl+R will refresh the page but worth a try

**Comment by glasnak** [comment]
Hi, I'm experiencing the same issue.
Ctrl+R does refresh the page but does not fix the issue.

**Comment by grok** [comment]
Installing on Ubuntu 18.04.3 LTS 64-bit
![image](https://user-images.githubusercontent.com/495761/104028529-d2e37b80-5196-11eb-86cb-87f627515792.png)
![image](https://user-images.githubusercontent.com/495761/104028655-fd353900-5196-11eb-9b62-50de4ea38264.png)
![image](https://user-images.githubusercontent.com/495761/104028676-02928380-5197-11eb-8e21-8e0028d9e81e.png)
![image](https://user-images.githubusercontent.com/495761/104028701-0cb48200-5197-11eb-9465-ed8baafbb6ab.png)

Even though it's a fresh install, I tried the CTRL+R, and just for giggles, CTRL+SHIFT+R and I get the same error.

**Comment by piotrekfus91** [comment]
Same for me. Some Googling shows that it may be relatively easy to fix for one knowing Electron: https://stackoverflow.com/questions/59685927/electron-application-using-google-oauth-this-browser-or-app-may-not-be-secure

**Comment by grok** [comment]
> Same for me. Some Googling shows that it may be relatively easy to fix for one knowing Electron: https://stackoverflow.com/questions/59685927/electron-application-using-google-oauth-this-browser-or-app-may-not-be-secure

For what it's worth:

> Apparently Google is restricting usage of Google sign-in in non-standard browsers (which presumably includes Electron) starting in Jan. 2021, and warns developers not to modify their browser's user-agent (which all three of the possibilities I mention do). Use at your own risk! (they don't make clear what outcome will result, but for my own use, I'm opting to use the alternative shown below from now on)
>
> As an alternative to using a Google sign-in popup in your app (which some might be wary of, since Electron apps could in principle insert code into the popup to read the raw password -- not that it matters that much, since Electron apps could just install keyloggers or the like anyway), you could instead open a tab in the user's regular external browser, pointed to a special page that triggers a sign-in popup there, and then just sends the credentials to your Electron app afterward.
>
> Instructions can be seen here (approach 3): https://stackoverflow.com/a/64328193/2441655
