### ISSUE TITLE
[BUG] Offline mode notification panel unreadable

### ISSUE THREAD

**Issue by tpondant** [KryDos/todoist-linux#109]
When I was on offline mode, I saw that there was a new icon at the top right corner of the todoist app. I moved my cursor to the red triangle icon there to see what it said, but I wasn't able to read the text in the panel displayed while hovering with the cursor over the red triangle icon, because the panel was flickering at a rapid pace.

See screen recording [here](https://u.pcloud.link/publink/show?code=XZGVD5XZA1x4Fmzz55RKvdpA8Fp2FLP1hFry).

What's really strange is that while I was setting up SimpleScreenRecorder on my OS, which is a default screen recorder software on Linux Mint, and I put my cursor on the same triangle I was talking about before (while the focus was still on SimpleScreenRecorder with the todoist app in the background), the panel wasn't flickering anymore and I could actually read what was in there.

I'm on Linux Mint Cinnamon 19.

P.S. I advise you to download the video I shared, because it was jerky when I played it directly in the browser.

**Comment by KryDos** [comment]
wow, what a nice bug!
Thanks for the report @tpondant, I'll try to reproduce it on my VM. I hope it will be easy to reproduce.
