### ISSUE TITLE
Can we get notification support?

### ISSUE THREAD

**Issue by ceiphr** [KryDos/todoist-linux#113]
Title. I think it would be great, and having Todoist start on boot would make this feature even more useful too.

**Comment by KryDos** [comment]
I like the idea. I don't know what kind of method they use to get those notification (websockets probably). I don't think we can directly subscribe to those notifications but we might listen for changes in their notification bar... what do you think?

**Comment by ceiphr** [comment]
That sounds like the right approach. I assume electron has some way to catch notifications, so we can relay them to the OS. I'm just unsure if we'd have to implement the relay or if electron would handle it for us.

I'll look into this further in the coming weeks.

**Comment by ceiphr** [comment]
Good news! This is already supported in this project. I had notifications disabled on my system for it before (I don't know why).
