### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by xepozz** [KryDos/todoist-linux#114]
Hi. I can't install a latest version of todoist.

The fail says that package needed `gconf2`, that depends on `gconf-service`, that depends on `libappindicator1` that depends on `gconf2` :)

```
$ uname -a

Linux xepozz-notebook 5.4.0-47-generic #51~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ lsb_release -a

No LSB modules are available.
Distributor ID:	elementary
Description:	elementary OS 5.1.7 Hera
Release:	5.1.7
Codename:	hera
```

![image](https://user-images.githubusercontent.com/6815714/94723714-daa6af00-0361-11eb-9c25-381ff2210bea.png)

**Comment by KryDos** [comment]
hey @xepozz, 
As far as I know dpkg doesn't install dependencies automatically. 
To install all the deps you must run `sudo apt-get -f install` (or `sudo apt -f install`). Make sure that you run this command after `dpkg`. Dpkg will kind of let apt manager know about what deps should be installed. 
Again, I'm not sure, but probably you don't need to run `dpkg -i Todoist...` again and it will be installed with `apt -f install`. 

Let me know if that `apt` command worked for you

**Comment by xepozz** [comment]
I've tried to manually install missed dependencies with usage `apt`. It doesn't work.

**Comment by vitperov** [comment]
> I've tried to manually install missed dependencies with usage `apt`. It doesn't work.

Try sudo apt install -f just after dpkg:
![image](https://user-images.githubusercontent.com/3582851/97695620-63298400-1ab5-11eb-8495-09f2361966d7.png)

**Comment by xepozz** [comment]
I've installed todoist from Snap.
