### ISSUE TITLE
[FEATURE REQUEST] Can't select tasks in board view

### ISSUE THREAD

**Issue by tpondant** [KryDos/todoist-linux#117]
**Issue**
Whlie in board view, I am unable to select a task or more than one tasks using Ctrl and my mouse.

**What is expected**
To be able to select one or multiple tasks at a time while in board view.

**What happens instead**
The task clicked is focused just like it would if you had just left-clicked on it in list or board view.

**How to reproduce**
1. Add project
2. Choose board view
3. Create a task or two
4. Maintain Ctrl key pressed and left-click on a task to select it.

**System info**
Ubuntu 20.04.1 LTS (Focal Fossa)

**Comment by KryDos** [comment]
hi @tpondant, 
I didn't use board view but it seems like the feature you have suggested should be pretty useful. 

Correct me if I'm wrong but it seems like there is no such functionality in Todoist itself. I'd like to not have any functionality in this wrapper that alter the original functionality of Todoist. 

I'd suggest to contact Todoist team directly. I'm not exactly sure where you can do it but I found this site - https://get.todoist.help/hc/en-us and it has "Contact Us" button.

**Comment by tpondant** [comment]
hello @KryDos,

I can't select tasks either on todoist.com, so I guess that, yes, it isn't implemented in Todoist itself.

I'll request this feature on their website, but they don't always answer to such requests. I'll let you know if I get an answer.

P.S.
I think you're right to wait for Todoist to integrate it into their product first. I prefer a product that works well with less features than a product that doesn't with more features :)
