### ISSUE TITLE
Icon in launcher is missing

### ISSUE THREAD

**Issue by xiaodl813** [KryDos/todoist-linux#119]
I'm using Deepin 20 as my Linux PC. After I installed the latest version,  I found that the icon of Todoist in launcher is missing and I can not fine the icon file in the installation directory (/opt/Todoist). I have checked the todoist.desktop file in /usr/share/application then found the Icon item is "todoist" instead of an absolute path. 
Could you please help me to find a solution of this problem?
Thank you very much!

**Comment by xiaodl813** [comment]
After several times reboot the icon comes back... However, I have no idea about what happened...

**Comment by KryDos** [comment]
Thanks for letting me know anyway, @xiaodl813. I'm happy you were able to fix it.
