### ISSUE TITLE
URL in task name is opening in non-default-browser (Chromium)

### ISSUE THREAD

**Issue by mikkovedru** [KryDos/todoist-linux#124]
* OS Linux Mint 20 Cinnamon (Based on Ubuntu 20.04)
* Cinnamon 4.6.7

I updated my OS from Mint 19.3 to Mint 20 and at the same time, I also updated all other programs, including todoist-linux (it has been some time since I last updated todoist-linux and I had to jump a few versions).

Now I noticed that the links that are in the task names are opening in a separate Chrome window (without address bar/menu/buttons/etc and without starting the main Chrome instance), instead of the default-browser Firefox. Pressing Ctrl or Shift together with clicking does not change the situation.

![image](https://user-images.githubusercontent.com/2521942/96353557-e6220600-10d5-11eb-9dbe-c42d66f27337.png)

**Comment by KryDos** [comment]
hm, I remember we had such issue before. It seems like regression of that bug. 
Thanks a lot for the issue creation.

**Comment by ceiphr** [comment]
Can confirm. Does it have something to do with how logins work?

**Comment by mikkovedru** [comment]
Mostly because of this issue (alt-menu issue also minorly influenced my decision) I decided to downgrade and go back to version 1.23.

**Comment by ceiphr** [comment]
Understandable. Hopefully we can get these issues resolved soon.

**Comment by ceiphr** [comment]
@mikkovedru I've written https://github.com/KryDos/todoist-linux/pull/128 and https://github.com/KryDos/todoist-linux/pull/129 to fix the problems you're experiencing. https://github.com/KryDos/todoist-linux/pull/128 is a quick fix until we can solve the problems with electron. https://github.com/KryDos/todoist-linux/pull/129 is a direct fix for this issue.
