### ISSUE TITLE
New menu (invoked by pressing ALT) conflicts with internal todoist's "edit task" function

### ISSUE THREAD

**Issue by mikkovedru** [KryDos/todoist-linux#125]
* OS Linux Mint 20 Cinnamon (Based on Ubuntu 20.04)
* Cinnamon 4.6.7

In todoist you can edit tasks by:
1. clicking on them. It opens a big full-screen window with a lot of options (subtasks, comments, activity).
2. Alt-clicking on them. This allows to quickly edit the name and some other major characteristics (priority, date)

Unfortunately, the creation of the menu (invoked by pressing ALT) in todoist-linux conflicts with the second option of alt-clicking. Every time I alt-click a task, the menu opens and doesn't go away until I press Alt at some point again.

**Comment by KryDos** [comment]
Good catch @mikkovedru, Thanks. 
I didn't know about alt-click type of editing. It sounds pretty nice. 

I hope it can be fixed quickly.

**Comment by mikkovedru** [comment]
Maybe @ceiphr could help fixing this issue?

**Comment by ceiphr** [comment]
Nice catch. This weekend I can look into this issue.

**Comment by ceiphr** [comment]
I can confirm this issue is reproducible. It is also an issue on Todoist's Official snap.

IIRC <kbd>Alt</kbd> is a hard-coded toggle in electron.

I've filed an issue on https://github.com/electron/electron to prevent the toggle on mouse click: https://github.com/electron/electron/issues/26149

AFAIK, our only option for now is to offer a setting in the config to disable zoom in/out/reset and the alt menu. Should we take that approach or wait for an upstream fix (which will probably take a while, given how popular electron is)?

**Comment by mikkovedru** [comment]
1. The response https://github.com/electron/electron/issues/26149#issuecomment-716075800 there says that we should try to update to a new supported version of the Electron and see if the issue is still present.

I guess this should be the first priority then. I don't know how complicated it is to update from the currently used Electron version to a new one...

2. I don't see a need to disable zoom in/out/reset or have such a setting. It's only the Alt menu that is the problem.

3. In general it sound unbelievable that there would be such an obvious bug in such a popular framework. So I assume that either the bug doesn't exist in a new version or that we just don't know how other people are doing menus in the right way. Because otherwise, all other `Alt + whatever-button` key combinations would not work (for example pressing `Alt+A` would do whatever the application set that combination to do, but when `Alt` is let go, the menu is still invoked).

4. Talking about the menu. Would be possible to add `Alt + specific-button` key combination in order to open a specific alt-menu? Look how it is done in Firefox:
![image](https://user-images.githubusercontent.com/2521942/97108756-2dad2100-16d8-11eb-99ce-a03fb1b73053.png)
I can press `Alt + S` and that opens a `History` menu. Todoist-linux doesn't have that:
![image](https://user-images.githubusercontent.com/2521942/97108761-3867b600-16d8-11eb-8f55-7dec541b4795.png)

5. If the issue can't be solved in other ways, config setting could be an option. Simply pressing `Alt` would do nothing, but one could still invoke the menu by pressing `Alt + F`, `Alt + V` or `Alt + H`.

**Comment by mikkovedru** [comment]
Here is what the Wikipedia article says about Electron versions. FYI todoist-linux uses version 4.2.12.
![image](https://user-images.githubusercontent.com/2521942/97109072-e758c180-16d9-11eb-94f6-c2c4c74e7e7e.png)

**Comment by ceiphr** [comment]
1. I'll make a branch on my fork to try and experiment with upgrading electron.
2. It is bizarre to say, but sadly the zoom functionality comes from the alt menu existing. I'm just invoking a role electron has set for the feature.
3. IIRC This is possible, but it wouldn't override alt, so you would have the alt toggle and another key binding for toggling as well.
4. This is possible and easy to implement: https://www.electronjs.org/docs/api/menu#menusetapplicationmenumenu
5. I agree, we'll make the config option a last resort.

I'll get back to this issue after I experiment with the electron upgrade.

**Comment by ceiphr** [comment]
Upgrading the electron dependencies doesn't resolve the issue:
https://github.com/ceiphr/todoist-linux/tree/update-electron

**Comment by m-danya** [comment]
Hi! Thanks for your hard work. I will be really appreciative, if you add the menu-disable option to config.

**Comment by m-danya** [comment]
Hi! I've set "toggle-menubar" to false in the config (i had to add it manually, there was no such a parameter), but the ALT button is still causes the menu to be displayed. Am I doing everything right?

**Comment by ceiphr** [comment]
@m-danya #129 has a bug I need to fix after final exams. If you want the version with the #128 fixes, pull and build https://github.com/ceiphr/todoist-linux/tree/feature-menubar-improvements. It will create `Todoist_1.24.0_amd64.deb` like you mentioned. Just reinstall the package and you should be set.

**Comment by m-danya** [comment]
Thank you, it works! I really appreciate your work!

The full sequence of steps I've taken is listed below, i think it can be useful for people, who want to get the alt-button problem fix:
```
sudo apt purge todoist
git clone https://github.com/KryDos/todoist-linux
cd todoist-linux
git fetch origin pull/128/head:test
git checkout test
make env
make up
make build-deb 
sudo dpkg --install dist/Todoist_1.24.0_amd64.deb 
```
