### ISSUE TITLE
Spaces between words in sidebar and project windows are too wide.

### ISSUE THREAD

**Issue by silverben10** [KryDos/todoist-linux#126]
I've noticed an odd spacing issue on some areas of text within the application. See the image for reference:

![image](https://user-images.githubusercontent.com/21127383/96609621-9d936400-12f2-11eb-8839-5e585f751633.png)

The areas I've noticed this problem affecting are:
- project names in the sidebar
- *Add Project* button in the sidebar
- Project titles in the main view (where all of a project's tasks are displayed)
- Task titles in the main view
- Task titles in a task view

**Comment by KryDos** [comment]
hey @silverben10, 
thanks for the report of this issue. 

I don't see such behavior but I'd like to test more. Could you please share what is the system you're using (windows or linux and if linux then what distro and what desktop environment) ?

**Comment by silverben10** [comment]
Of course, thanks for the quick reply!

* OS: Linux
* Distro: Arch
* DE: KDE

I can try reinstalling it and see if the issue persists?

**Comment by KryDos** [comment]
Thanks! 
I don't think re-installation will help, it may be related to system font and its interference with the original font the app is using. But it's just a guess. I'll try to install kde to my test machine (not arch though) and I get back to you with more info. 

If you can find what font do you use in KDE that would be helpful

**Comment by silverben10** [comment]
Ok, sounds good. Here are the font settings for my DE.

![image](https://user-images.githubusercontent.com/21127383/96612840-2bbd1980-12f6-11eb-89ca-f05e3519a953.png)

I downloaded the fonts using [this](https://aur.archlinux.org/packages/otf-san-francisco/) AUR package
