### ISSUE TITLE
Suggestion: zoom in/out using Ctrl + Mouse Wheel

### ISSUE THREAD

**Issue by mikkovedru** [KryDos/todoist-linux#127]
I would like to suggest an addition to this ( `Added zoom in/out support with shortcuts and menubar` ) commit https://github.com/KryDos/todoist-linux/commit/32920cb47ed2203f789f2a0b000863b568dbcbf1 by @ceiphr.

In it, `Ctrl+'+'` and `Ctrl+'-'` shortcuts were added to zoom in and zoom out the content of the app.

It would be nice to be able to access the same functionality using `Ctrl+MouseWheelUp` and `Ctrl+MouseWheelDown` respectively.

**Comment by ceiphr** [comment]
I like the idea and it seems do-able:
https://stackoverflow.com/questions/40262110/zoom-with-ctrlscroll-wheel-in-electron-app

I'll see if I can make a PR before monday.

**Comment by ceiphr** [comment]
After further research, I'm actually not sure how to properly implement this feature.

This issue is the block I'm stuck on:
https://github.com/electron/electron/issues/12436

@mikkovedru please let me know if you can find an approach that works.

**Comment by mikkovedru** [comment]
@ceiphr 
Seems like a real bug. And it seems that Electron developers won't do anything until todoist-linux is updated to the modern version of Electron and the bug is confirmed once again.

**Comment by ceiphr** [comment]
When I try to leverage `addeventlistener` the way they did, electron tells me it isn't a function. 

I'll try to get a working version pushed on my fork this week, so I can confirm the bug on https://github.com/electron/electron/issues/12436.

@mikkovedru please let me know if you can find a way to get `addeventlistener` working with `BrowserWindow`.
