### ISSUE TITLE
[BUG] Can't reorder tasks in board view on todoist linux

### ISSUE THREAD

**Issue by tpondant** [KryDos/todoist-linux#135]
How to reproduce?

1. Create a board project.
2. Add tasks.
3. Try to change the position of tasks in a same column

The tasks cannot be moved.

**Comment by stefan2904** [comment]
This happens when you have some sorting enabled, for example "sort by priority". Apparently this is currently by design, as the Todoist support told me. Are you sure this is not the case in your case?
