### ISSUE TITLE
[Feature Request] Full screen Mode

### ISSUE THREAD

**Issue by saikatm** [KryDos/todoist-linux#16]
If you use todoist on browser like Google Chrome if you go fullscreen(F11) then the todoist web app looks really nice and minimal. I think it is not hard to get fullscreen mode with the electron? 😊 please bring a total fullscreen mode! thanks.

![image](https://user-images.githubusercontent.com/9909763/43678134-33124a2c-982b-11e8-86dd-a648a31c55e1.png)

**Comment by KryDos** [comment]
@saikatm thanks for this request! I'll try to make it asap

**Comment by KryDos** [comment]
hi @saikatm,
I'm sorry for such a delay on this feature. 

[In the latest version](https://github.com/KryDos/todoist-linux/releases/tag/1.14) you can toggle Full Screen mode with `F11` (or using menu in Tray icon).
