### ISSUE TITLE
Obey XDG standard for .todoist-linux.json file

### ISSUE THREAD

**Issue by Omar-Elrefaei** [KryDos/todoist-linux#17]
Please use the `$XDG_CONFIG_HOME` environment variable or `$HOME/.config` as a fallback for the `.todoist-linux.json` in order to avoid cluttering the users home dir, and that will greatly help when I am trying to manage my configuration across different machines/distros.

You can more context about the standard at the [XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)
and the frustration [here](https://github.com/KryDos/todoist-linux/issues/new)

**Comment by KryDos** [comment]
wow! I didn't know about that variable. I'll try to change it asap. Thanks a lot!

**Comment by KryDos** [comment]
Hey @Omar-Elrefaei 
I've just updated the code to respect the `$XDG_CONFIG_HOME` variable. In case the variable isn't set then `$HOME/.config` will be used (as it is stated in Spec). 

[The released version is here](https://github.com/KryDos/todoist-linux/releases/tag/1.10)

Let me know if still have any issues with it.

**Comment by Omar-Elrefaei** [comment]
Thanks that's awesome
