### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by Omar-Elrefaei** [KryDos/todoist-linux#18]
I don't know much about electron, but I was wondering if it is a chrome wrapper can you somehow bundle extensions with the app. This is extension had proven really useful to me, [Todoist-Shortcuts](https://github.com/mgsloan/todoist-shortcuts), it provides keyboard shortcuts for efficiently manipulating tasks and navigating inside todoist. I would be really happy if I could use it from the app

**Comment by KryDos** [comment]
@Omar-Elrefaei my suggestion for you is to use Chrome with `app mode`. 

You need to run it like that:
`path\to\chrome\chrome --app=https://todoist.com/app`. 
Then the new instance of chrome will serve only todoist app. 
I believe every extension installed in your chrome should be working.

**Comment by Omar-Elrefaei** [comment]
Yeah it does. You if you are interested you could look into providing your
own shortcuts. Thanks anyway

**Comment by cyfrost** [comment]
@KryDos can this issue be closed?

**Comment by KryDos** [comment]
definitely. Thanks @cyfrost
