### ISSUE TITLE
Opens todoist in the current browser not in the dedicated window!

### ISSUE THREAD

**Issue by NinjaTurtle007** [KryDos/todoist-linux#19]
It opens a dedicated window but after logging in it gives:
You have been logged in. Click here if you are not auto redirected.

It doesn't auto redirect and when you click the link it opens todoist in the currently running browser (firefox)

so it can't  be used in the dedicated window for some reason

**Comment by KryDos** [comment]
Brilliant! thanks for the report. I saw this issue previously too. 
You are actually logged in and when you will close the app and open it again you will be logged in correctly.

I'll try to fix this issue and let you know when it's done.

**Comment by NinjaTurtle007** [comment]
I tried reopening the app multiple times but it always showed the same window with the message about being redirected only.

**Comment by KryDos** [comment]
Then it means the app wasn't closed. It just was hidden to the tray and then was appeared again. It has to be completely restarted.

**Comment by NinjaTurtle007** [comment]
ok so the minimize to tray in gnome 3.30.1 doesn't work either

**Comment by KryDos** [comment]
Awesome! thanks for the report I'll create the separated issue.

**Comment by drmercer** [comment]
@NinjaTurtle007 Tray icons don't show by default in modern Gnome - see my comment on #21 for solutions. :slightly_smiling_face:
