### ISSUE TITLE
[Feature Request] Add download options

### ISSUE THREAD

**Issue by AlexeyKot** [KryDos/todoist-linux#2]
Thanks for you app!
It would be great if you add download options like: .deb, .rpm, snap, flatpak, .appimage

**Comment by KryDos** [comment]
hey, thanks for the feedback. Sure it make sense. 

Do you know any publicly available systems (maybe docker image(s)) that can help me to build multiple packages for different distros? 

The only way I see is to have multiple VMs with different distros and build the package for particular distro using its build-tools. I'm ok to maintain deb-based and rpm-based distro, but I'm not sure about more.

I'll update the ticket when at least deb package will be available.

**Comment by klauscfhq** [comment]
The [electron-builder](https://github.com/electron-userland/electron-builder) module can be utilized for this purpose quite easily, and be integrated with a CI; like [travis](http://travis-ci.org/) or [appveyor](http://appveyor.com), to build and release all needed binaries. [Docker support is also included](https://www.electron.build/multi-platform-build), here are a couple of links to dig deeper: 

- [Electron-builder API docs](https://www.electron.build/)
- [Step by step tutorial](http://electron.rocks/electron-builder-explained/)

Hope it helps out : )

**Comment by KryDos** [comment]
Hi guys. 

I was finally able to build DEB and RPM packages locally on my machine. 

I've updated latest release with both packages here - https://github.com/KryDos/todoist-linux/releases/tag/1.3

took quite long time to make icon appear correctly for the app, but should be ok now. 
I'm closing the issue for now. Feel free to reopen it.

**Comment by AlexeyKot** [comment]
Cool, thanks! Already using your .deb package.

By the way, on README.md you named download options is "Debiana" instead of "Debian" and the link goes to your dropbox, rather then github hosting as on Release page.
