### ISSUE TITLE
Still opens a window with ctrl+alt+t even after uninstalling.

### ISSUE THREAD

**Issue by NinjaTurtle007** [KryDos/todoist-linux#20]
I uninstalled the deb but even after that it still opens the todoist window when ctrl+alt+t is pressed
what kind of sorcery is this? :)

**Comment by KryDos** [comment]
Hi @NinjaTurtle007,
Uninstalling the deb package isn't closing the app. The app is definitely still running. 
You can find it with `ps -A | grep -i todoist` and then kill it by PID. 

The app actually has to be in your tray where you can close it. If it's not there then it's another bug.

**Comment by NinjaTurtle007** [comment]
yup, that worked, thank you!
