### ISSUE TITLE
The app is not showing up in Tray on Gnome 3

### ISSUE THREAD

**Issue by KryDos** [KryDos/todoist-linux#21]
reported here - https://github.com/KryDos/todoist-linux/issues/19#issuecomment-434958405

**Comment by drmercer** [comment]
Tray app icons don't show in Gnome 3 by default. [This Gnome extension](https://extensions.gnome.org/extension/615/appindicator-support/) fixed the problem for me. See also [this question on Ask Ubuntu](https://askubuntu.com/questions/651367/how-to-get-indicators-back-in-top-panel-on-gnome-3).

**Comment by KryDos** [comment]
Wow, thanks a lot @drmercer, I didn't know about that.
