### ISSUE TITLE
Adding task: projects are not showing Emoji

### ISSUE THREAD

**Issue by mikkovedru** [KryDos/todoist-linux#22]
My projects are using Emojis to improve visibility. Emojis work properly in the Project view:
![image](https://user-images.githubusercontent.com/2521942/51177054-48c5ec80-18c7-11e9-9ade-f3e02bb3691b.png)

But when I try to add a task to a project (by writing shortcut "#"), the displayed projects are no longer showing Emojis:
![image](https://user-images.githubusercontent.com/2521942/51177034-351a8600-18c7-11e9-883f-4de6de770bc4.png)

**Comment by KryDos** [comment]
hi @mikkovedru,
thanks for the report!

Are these Emojis working inside web version of Todoist? 

The app is just wrapper for their web version and in case something isn't working there it should be pretty hard to fix on our side.

**Comment by KryDos** [comment]
ok, I'll try to check this issue. I see that Programming project has emoji displaying but other projects won't display an emoji. Pretty interesting. 

I'll take a look.

**Comment by mikkovedru** [comment]
That's interesting indeed! Didn't notice that myself. :-)

To help, here is a list of some of the emojis I use:
- :couple: Sharing-caring Tasks
- :man: Personal
- :memo: Errand
- :mortar_board: Study
- :family: Family & Friends
- :muscle: Sports/Health
- :trophy: Rewards
- :computer: Work/Business
- :microphone: Standup
- :dart: Goals
- :keyboard: Programming

**Comment by KryDos** [comment]
hi @mikkovedru 
I was trying to reproduce it but no luck. 

Is there any way you can restart the app (I know you did it but...) in the next way:

* close it
* make sure it is not running in the background (`ps -A | grep -i todoist`)
* kill it if it's running
* run it again

**Comment by mikkovedru** [comment]
@KryDos 
I found the problem and I was able to fix it! Here are the details in case anyone will encounter a similar problem.

Operation System: Linux Mint 19.1 Cinnamon. 

In Firefox everything works fine. But the problem is that todoist-linux app is build upon Chrome's browser engine. I ran Chromium and it had exactly the same problem as todoist-linux app. The problem had to do with fonts.

I fixed it by install the `fonts-noto-color-emoji` package (in Ubuntu/Linux Mint run the command `sudo apt install fonts-noto-color-emoji`). Restarting the application (or Chrome/Chromium) fixes the issue.

If it doesn't in your case, you can try way more complex solutions [here](https://askubuntu.com/questions/1029661/18-04-color-emoji-not-showing-up-at-all-in-chrome-only-partially-in-firefox).
