### ISSUE TITLE
Suggestion: default global shortcut to hide/show the app should be changed 

### ISSUE THREAD

**Issue by mikkovedru** [KryDos/todoist-linux#23]
Currently the default shortcut is Ctrl+Alt+T.

But it seems to me that in quite many Linux versions that shortcut is already in use - it opens a Terminal window. 

I suggest that the Todoist-Linux's default shortcut be changed to something else - for example Ctrl+Alt+Q.

**Comment by KryDos** [comment]
@mikkovedru thanks for this suggestion. It definitely make sense to change the defaults, since as far as I remember in current Gnome3 Ctrl+Alt+T is, as you mentioned, terminal app. 

As a quick solution you can change Ctrl+Alt+T to something else in your `$XDG_CONFIG_HOME/.todoist-linux.json`.

**Comment by mikkovedru** [comment]
Thank you for the suggestion. I already did that, even before writing this Issue. 

But it's better to have the most sensible default settings so people wouldn't need to do extra work. :-)
