### ISSUE TITLE
Suggestion: remember window position/size/monitor/workspace after restart

### ISSUE THREAD

**Issue by mikkovedru** [KryDos/todoist-linux#25]
I have a two-monitor set-up and todoist-linux always opens (when started initially) on the wrong one. This is irritating.

I also have a very specific place where I want the todoist-linux window to be (right side of my left monitor; taking full height and about 30% of the width). Every time I open todoist-linux for the first time, I have to spend time relocating the window.

My suggestion is for the program to remember all its position/size/monitor/workspace and always restore those.

**Comment by mikkovedru** [comment]
@KryDos 
Linux Mint 19.1 Cinnamon. 

I am sure that this must be the app side thing, because:
1. I haven't seen any settings, where this kind of thing could be turned on
2. Some apps remember their position (like Telegram Desktop), while others don't.

I would compare it to "start the app as minimized" situation: some apps can do it, some can't.

I don't know how to do it though. :-(

**Comment by mikkovedru** [comment]
Quick googling gave these links:
https://github.com/mawie81/electron-window-state
https://github.com/electron/electron/issues/526

So it is possible! Hurray!

**Comment by KryDos** [comment]
nice! Thanks! I'll try to play with ideas suggested there

**Comment by mikkovedru** [comment]
This is a nice post, which describes all the steps you need to do (there are also other tips that you might find useful and might want to implement):
https://blog.avocode.com/4-must-know-tips-for-building-cross-platform-electron-apps-f3ae9c2bffff

**Comment by KryDos** [comment]
hi @mikkovedru 
Please check out version 1.12 [HERE](https://github.com/KryDos/todoist-linux/releases/tag/1.12)

I've used the library you found [electron-window-state](https://github.com/mawie81/electron-window-state). 
It seems the app now can remember window position and its size. 
Unfortunately I can't check if it works for two or more monitors but for one monitor it works pretty well.

Let me know if it works for you and we can close this ticket then.

**Comment by mikkovedru** [comment]
The whole program doesn't even start.

> A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electron-window-state'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/opt/Todoist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/Todoist/resources/app.asar/main.js:2:27)
    at Object.<anonymous> (/opt/Todoist/resources/app.asar/main.js:125:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

**Comment by KryDos** [comment]
oh lol. I've just checked it on different laptop and got the same error too...

**Comment by mikkovedru** [comment]
Good. So I don't need to spend time investigating why doesn't it work on my computer. :-)

Maybe you should release such untested version as betas, not as full-fledged releases? It would be a pity if a new person would try to set-up his Linux system, be unfortunate enough to download the broken version 1.12 and decide that it's his fault (or that this app is broken and is not worth his time).

**Comment by KryDos** [comment]
Sure that's would be good to have better way of releases and have beta and stable ones. 
But at the same time this project has very small amount of users and especially developers which work on it. I just don't feel it's time to setup something like this. Maybe one day though.

**Comment by KryDos** [comment]
I've just updated binaries attached to the release. You can try to re-download the version you use. Sorry about that

**Comment by mikkovedru** [comment]
The new version works very well! Thank you!

This issue can be closed as far as I am concerned.
