### ISSUE TITLE
Suggestion: Tray: The app should be showed/hidden with one mouse click

### ISSUE THREAD

**Issue by mikkovedru** [KryDos/todoist-linux#28]
Linux Mint 19.1 Cinnamon.

Currently in order to open the app using tray icon, I need to click on the icon with my right mouse button and choose "Show". Left click does nothing. Double click does nothing either.

It would be nice to be able to show and hide the app by one left click of the mouse (like Telegram Desktop app does).

**Comment by cyfrost** [comment]
@KryDos Regarding this issue, Electron uses `libappindicator` if found in the system, in which case it ignores the `click` event.

![image](https://user-images.githubusercontent.com/12471103/54473003-df475900-47f7-11e9-828a-6fe07b2f3628.png)

more info here: https://electronjs.org/docs/api/tray

**Comment by Dude29** [comment]
I think double clicking the tray icon to bring the app into foreground would be an acceptable solution.
@KryDos Do you agree? I can attempt to implement this

**Comment by mikkovedru** [comment]
@Dude29 
I personally agree that this would be a definite improvement over the current situation.

**Comment by KryDos** [comment]
@Dude29 sure, I have no objections on this. Definetly should be much more user-friendly if we use one-click.

**Comment by Dude29** [comment]
I am afraid I have sad news...

As expected the tray click functionality is not supported on Linux for this version of Electron(4.2.12). It is supported on some of Electron's versions, like 9.0.2 for example, but it's behavior is inconsistent. 
I tested it on 9.0.2 and on 8.2.2 and I found that sometimes the clicks come with delay and other times they aren't registered at all. What's worse is that upgrading Electron to these versions breaks some of the app's global shortcuts so I don't think this is a proper solution at all.
The same thing happens for the double click event and, as far as I can tell, all mouse events on the app tray. [Here](https://github.com/Dude29/todoist-linux/pull/2) is the code I tested with.
More info [here](https://github.com/electron/electron/issues/14941)

So the way I see it we have some options:
- Wait for Electron to support this feature
- Write our own native module to interact with the tray(I don't have the knowledge for this)
- Leave it as is

What do you think?

**Comment by Dude29** [comment]
I forgot to mention that I only tested this on Ubuntu 20.04 which uses libappindicator

**Comment by KryDos** [comment]
wow @Dude29, good research. Thanks! I would leave it as is right now, it works and it's good. Can be better but don't worth the time at least for now. 

I'll keep this issue open for future discussion.

**Comment by kendoori** [comment]
Given that it seems not possible to single or double click on the tray to show/hide ToDoIst, I would love a way to bind "Open Todoist" to a keyboard shortcut.

**Comment by kendoori** [comment]
> Given that it seems not possible to single or double click on the tray to show/hide ToDoIst, I would love a way to bind "Open Todoist" to a keyboard shortcut.

Discovered via preferences that this works: 
**"show-hide": "CommandOrControl+Alt+Q",**
