### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by saikatm** [KryDos/todoist-linux#3]
I know this builds are only for Linux. As it is based on electron it is easy to also make WIndows Build.
Please release builds for windows too. I would really appreciate that!

**Comment by KryDos** [comment]
Hi @saikatm, 
hm, didn't think about actually. 

As far as I know Todoist has official client for Windows. Take a look here - https://todoist.com/downloads
I'm pretty sure official windows version is going to be much more optimized than the current version wrapped with Electron. 

Is there any reason you see I should make windows version as well?

**Comment by saikatm** [comment]
@KryDos Todoist has two apps for windows. one is a UWP app from the windows store and the other one is a web wrapper. but it lacks a lot of functionalities. It doesn't even have offline Support.

can you make your electron builds offline support? todoist is fully offline supported on every browser.
thanks.

**Comment by KryDos** [comment]
hey @saikatm 

I was able to build win app with electron-builder and wine. Don't you mind to check if it actually works on windows since I don't have it. 

If it works I'll update readme file and add it to releases. 

[You can download it from here](https://www.dropbox.com/s/yyozom3x5agda9u/Todoist%201.4.0.exe?dl=0) - it's my dropbox.

**Comment by saikatm** [comment]
@KryDos Thank you so much I installed and tested it works fine and it is supporting offline mode omg!! Better than the official todoist web wrapper.

But there is some issue:

- after installing the app it does not create any shortcut in Desktop or In the Windows start menu, So I can't launch it after I quit the app. Also, I don't in which folder it gets installed so I can make a shortcut to the desktop, Please help me.
- I tried pinning the app on the taskbar but after quitting the app the shortcut doesn't work.

![image](https://user-images.githubusercontent.com/9909763/39748063-b2829c8e-52cc-11e8-987a-dca0f49a5cd1.png)

**Comment by KryDos** [comment]
brilliant, thank you for the testing! 

The app has no installator and it is basically portable version. The place where you have downloaded it, is install folder of the program. You can move it to any other folder but in this case any shortcut created (e.g. task bar icon) should be updated as well (removed and added again). 

I'm not sure if I can build the app that can be installed and that will create start menu shortcut, but I'll check it. 

Thanks again!

**Comment by saikatm** [comment]
Thank You. Even though it is a portable version I have checked disconnecting & rebooting my pc the offline mode works! really loved it.

And I have created a shortcut of the .exe file and pinned in the start menu and it is working well I can lunch it from there.

Some feature request: a reload option in the tray menu and Global shortcut key combination showing and hiding the app would be nice.
hope to see get it better over time! Good luck and Thank you! 🥇 💯 👍

**Comment by KryDos** [comment]
Cool, glad you like it. 

I'll close this issue then and create new for global shortcut to "show/hide" the app and for reload. 

You want just page reload shortcut? what is the reason and use case of it?

**Comment by saikatm** [comment]
sometimes the web app gets stuck or glitches so reloading the web app would fix it instantly.
and a global show-hide will be handy for quickly checking todoist and hiding it.

Official todoist has these option and it is really useful.
![image](https://user-images.githubusercontent.com/9909763/39750133-15839504-52d2-11e8-8dca-690cb27ac1cf.png)

**Comment by KryDos** [comment]
awesome! thanks a lot for the screenshot so I can keep the same keybinding. 

I'll let you know when some progress will be made. I guess I'll update readme file with link to exe as well. 

Thanks again!

**Comment by saikatm** [comment]
Sure mate!! you are doing a great job.
Also, add the windows build links to release page.
I am here if you need some testing 👍
