### ISSUE TITLE
Invalid or Missing CSRF token

### ISSUE THREAD

**Issue by TejasAvinashShetty** [KryDos/todoist-linux#30]
Whenever I try to login to todoist desktop it opens a page in my browser (here firefox). The page just displays a dialog box with the error "Invalid or Missing CSRF token"

**Comment by KryDos** [comment]
hi @TejasAvinashShetty, thanks for letting me know.

Are you trying to log in with login/pass or through google?

**Comment by TejasAvinashShetty** [comment]
Yes. 
Sorry, I  think a similar issue has been posted earlier.
[https://github.com/KryDos/todoist-linux/issues/15#issue-345564267](url)
I really should have searched better for similar issues before opening a new issue.

**Comment by KryDos** [comment]
Don't worry. I'm closing this one and I hope that https://github.com/KryDos/todoist-linux/issues/15 will be fixed soon

**Comment by TejasAvinashShetty** [comment]
Great

Regards,

Tejas Shetty
B Tech.Pharma
Department of Pharmaceutical Science and Technology
Institute of Chemical Technology, Matunga,
Maharashtra, India.
Contact No.: +91 9987015305,9004350057,8450978380,022 25582905
Email ID: tejasshetty.1808@gmail.com


*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*
