### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by JakubTetek** [KryDos/todoist-linux#31]
For the DEB package, this shows: "404 That file isn’t here anymore".

**Comment by KryDos** [comment]
hi @JakubTetek, 
thanks for the report. Could you please let me know where exactly this one is happening? Immediately when you open the app?

**Comment by KryDos** [comment]
Ah, got it. The link to DEB package.

**Comment by KryDos** [comment]
I'll fix the readme file. Meanwhile you can get the deb package on releases page - https://github.com/KryDos/todoist-linux/releases

**Comment by KryDos** [comment]
thanks again @JakubTetek, I've changed the readme file.
