### ISSUE TITLE
NOOB QUESTION: How could I install this on Arch?

### ISSUE THREAD

**Issue by ChausseBenjamin** [KryDos/todoist-linux#33]
I'd want to be able to start it with DMenu... I did make up to install it locally in the folder, how do i install it globally?

**Comment by KryDos** [comment]
hey @ChausseBenjamin,
thanks for trying this project. 

I believe your DMenu looks for executables in paths defined in $PATH variable. 

The simplest thing to do is just make a symlink somewhere in `/usr/bin` to the local folder of the app. 
Something like that:

```bash
ln -s /absolute/path/to/local/todoist /usr/bin
```
You probably need `sudo` for this.
