### ISSUE TITLE
Add ability to build RPM only in Makefile

### ISSUE THREAD

**Issue by DepthDeluxe** [KryDos/todoist-linux#34]
It looks like `build-all` attempts to build all Linux flavors of the application both .deb and .rpm but on my RHEL 7 host, I do not have (and do not want to install the .deb).  Perhaps it would be good to split out the Makefile to have the build commands `build-win`, `build-deb`, `build-rpm` that allows for building the desired versions separately.

**Comment by KryDos** [comment]
hi @DepthDeluxe 
sounds like good idea. It would be great if you can send a PR. 

You don't need Makefile to build RPM package though. You can copy the command from `build-all` target and extend it a bit. 
Command to build RPM package only is:

`./node_modules/.bin/electron-builder --linux rpm`
