### ISSUE TITLE
CSRF Token (Facebook login)

### ISSUE THREAD

**Issue by versipellis** [KryDos/todoist-linux#42]
Same as #15 and #30 I'm guessing, but this time with Facebook account.

**Comment by KryDos** [comment]
hi @versipellis, 
thanks for the report. 
I actually missed that there is facebook login possible and didn't make anything to make it working. 

I'll take a look.

**Comment by KryDos** [comment]
hey @versipellis,
excuse me for delay.

[Here is version 1.17](https://github.com/KryDos/todoist-linux/releases/tag/1.17) where facebook login should work.
