### ISSUE TITLE
Is it possible to make links open in Firefox instead of Chromium?

### ISSUE THREAD

**Issue by stefthoen** [KryDos/todoist-linux#49]
I have Firefox currently set as my default browser, but Todoist opens links in Chromium. Is there a way for it to respect my default browser?

**Comment by KryDos** [comment]
hi @stefthoen 
it actually should respect your default browser. There is no place where Chromium is hardcoded in the app.

What distro and desktop environment you are at?

**Comment by stefthoen** [comment]
@KryDos Ubuntu 18.04.2 LTS and desktop environment is Gnome.

![image](https://user-images.githubusercontent.com/881521/60884079-50e65f80-a24c-11e9-8219-5048c93ebe8d.png)

![image](https://user-images.githubusercontent.com/881521/60884123-72dfe200-a24c-11e9-8970-38f5eaf450c4.png)

**Comment by KryDos** [comment]
Brilliant! thanks @stefthoen for sharing screenshots. 
I've just played with different env variable settings and default application settings but cannot reproduce it still. 

Could you please share screenshot of default applications (press "win" button and type "default app"), and output of `echo $BROWSER`. Output of `xdg-settings get default-web-browser` also will be pretty helpful.

**Comment by stefthoen** [comment]
![image](https://user-images.githubusercontent.com/881521/61109164-89707e00-a484-11e9-8a37-93974617c1ce.png)

`echo $BROWSER` doesn't do anything, but the output of the `xdg-settings` you mentioned returns `firefox.desktop`.

**Comment by tukusejssirs** [comment]
Just to note that on Fedora 32 x86_64 with GNOME 3.36.3 with FF Nightly, FF and Chromium installed—and this app opens any link I click on in the default browser (FF Nightly).

`BROWSER` variable is not defined on my system (and I don’t believe that Fedora nor Ubuntu sets it by default). And `xdg-settings get default-web-browser` outputs `userapp-Nightly-SSGBC0.desktop`, which is correct to my preference. ;)
