### ISSUE TITLE
Why not put the arch version in AUR for further install and update convenience?

### ISSUE THREAD

**Issue by HadiLatifi** [KryDos/todoist-linux#50]
Hi, I was just wondering if this exists in AUR, searched for it and no luck. Are you planning to add it?

**Comment by KryDos** [comment]
hey @HadiLatifi,
I actually didn't plan it. I guess it's good idea. I'll take a look what I can do. 

I guess I need to make PKGBUILD or something like that...

**Comment by HadiLatifi** [comment]
yes, actually it's pretty easy and straight forward, you'll need to make a PKGBUILD and then upload it to AUR.
you could use **debtap**, a script for converting .deb to arch packages. it can help you by producing the PKGBUILD file, just be careful about the dependencies. it creates a lot of unneeded ones.
about creating the PKGBUILD you can see this [link](https://wiki.archlinux.org/index.php/creating_packages)
I'd be happy to help

**Comment by KryDos** [comment]
hey @HadiLatifi,
unfortunately still can't find time to work on it. Feel free to make PR with PKGBUILD. I can then add it to AUR.

**Comment by HadiLatifi** [comment]
hey @KryDos,
I've made the PR. just mind the already existing todoist clients on aur. esp for naming. also I'd suggest reviewing my PKGBUILD namings. the .SRCINFO is auto created by makepkg and is required by aur.

**Comment by lokesh-krishna** [comment]
Could you please update the AUR package to the latest release?

**Comment by KryDos** [comment]
hey @lokesh-krishna, 
I just made a new release (1.21) and pushed that to AUR as well. 

I should definitely automate it somehow because I'm always forgetting to update AUR. Thanks for reminding me.
