### ISSUE TITLE
Javascript execution by a click

### ISSUE THREAD

**Issue by luigigubello** [KryDos/todoist-linux#54]
In Todoist you can add website as task. So, you add a new task in the Todoist web app and paste the payload ```[TEST](javascriptjavascript::alert&#40document.cookie&#41)```. Now in todoist-linux (Electron based app) click on your task _TEST_ and an alert box with your cookies appears.

**Comment by KryDos** [comment]
hey @luigigubello,
thanks for this catch and I'm sorry for such a late response. 
On the todoist web version instead of alert I have new tab opened with `javascript:alert(document.cookie)` in URL but no alert. 

I'll take a look what I can do in the app to prevent this XSS issue.

Thanks again.
