### ISSUE TITLE
.deb installation file is not working in Ubuntu 19.10

### ISSUE THREAD

**Issue by mikkovedru** [KryDos/todoist-linux#56]
I tried to install the .deb version of the latest Todoist Linux 1.17 in the latest Ubuntu 19.10, but it failed.

While googling for the error message, I encountered this post:
https://www.medo64.com/2019/11/ubuntu-19-10-fails-to-install-deb-file/

Might the solution in the post above also solve the error with todoist-linux?

**Comment by KryDos** [comment]
Interesting. I'm installing Ubuntu 19.10 on my machine right now and let's see if I can reproduce and fix this issue.

Good catch!

**Comment by KryDos** [comment]
hey @mikkovedru,

I've been trying to reproduce it but no luck. It seems working on Ubuntu 19.10 which I just installed. 

The issue you mentioned is probably related to broken deb file. I got this one during the testing when download of the file was cancelled (by github I guess, I didn't cancel anything). 

Make sure the checksum of the file is `4a307dc2e26443dce0f593501521542d3e7a263c` (check with `sha1sum Todoist_1.17.0_amd64.deb`)

**Comment by mikkovedru** [comment]
@KryDos 
You were right! The download was getting corrupted every time I tried to download it with this new laptop. Therefore I downloaded the file on another computer, moved it to the new one, and everything started working as intended.

Thank you for spending time investigating this issue!

**Comment by KryDos** [comment]
Awesome! Closing this issue then
