### ISSUE TITLE
global shortcut to hide/show the app

### ISSUE THREAD

**Issue by KryDos** [KryDos/todoist-linux#6]
ref - https://github.com/KryDos/todoist-linux/issues/3

It would be great to have global short cut to show or hide the app from/to tray

see the screenshot attached here - https://github.com/KryDos/todoist-linux/issues/3#issuecomment-387346101 to use same keybinding as official client

**Comment by KryDos** [comment]
hey @saikatm 
I've just added shortcut for hide and show the app window (`CTRL+ALT+T`).

It looks useful for me too, so thanks a lot for the idea. 

The project's readme file was updated with link to exe file and also you can find EXE on releases page [here](https://github.com/KryDos/todoist-linux/releases)

**Comment by saikatm** [comment]
Thank you so much!! Keep up the good work. 👍
