### ISSUE TITLE
Aur not updated

### ISSUE THREAD

**Issue by tobinstultiens** [KryDos/todoist-linux#60]
The aur version has not been updated since 1.17 that means google authentication does not work. as show in issue #59 .

**Comment by KryDos** [comment]
Thanks for report @tobinstultiens 
It probably make sense to just make "todoist-git" kind of package so the latest code is automatically pulled all the time. 
I'll let you know when it's done. 

Meanwhile you can download pacman package from [latest release](https://github.com/KryDos/todoist-linux/releases) to solve that issue with login.

**Comment by tobinstultiens** [comment]
It has been updated
