### ISSUE TITLE
Suspending my pc causes it to stop updating

### ISSUE THREAD

**Issue by tobinstultiens** [KryDos/todoist-linux#64]
I don't know if this is something you can solve. But this is an issue that I've encountered where after suspending my PC it will no longer update the tasks. This requires met to refresh todoist with ctrl + alt + r.

**Comment by KryDos** [comment]
Wow. That's interesting. I'll try to reproduce it and fix it. I'll let you know the result.

**Comment by tobinstultiens** [comment]
if you need some more info you can ask.
i'm using manjaro xfce. if this can help with tracing the bug.
Also most of the time i suspend my pc it's for around half a day.

**Comment by KryDos** [comment]
hey @tobinstultiens,

I've tested this case in my Manjaro VM with XFCE. 

My steps were:

* run the app
* put VM to sleep mode
* wake the VM up
* add a task 
* open web version of todoist to see if that task is appeared there (it is)
* delete the task from todoist web version
* the task was automatically deleted in the running app too

Seems working. Could you please validate my steps. Also let me know please what exactly is happening when you say "the app is not updating". Do you see any message or anything like a loading animation next to the task?

Thanks

**Comment by tobinstultiens** [comment]
Hey @KryDos ,

I've tested it in the same way as you and there were no issues.

I'm going to do another test tomorrow. Since my laptop will have been suspended for a while. I think this may be the cause of the bug. Although when I booted it up to test it the moment I tried to add something it updated again.

I will update you tomorrow checking if the duration of the suspension is related to the freezing of the program that makes it stop updating and therefore require a refresh.

**Comment by tobinstultiens** [comment]
Hey @KryDos,

I think this might be related to the change of day during the suspension since those are the times it stops updating. Yet the moment when i add a task to todoist it fixes itself and syncs properly. So the simple act of adding a task can fix the syncing issue.
