### ISSUE TITLE
libappindicator-sharp does not exist in Archlinux

### ISSUE THREAD

**Issue by 183amir** [KryDos/todoist-linux#66]
Trying to install the `.pacman` file in archlinux:
```sh
$ sudo pacman -U /tmp/Todoist-1.19.0.pacman                                                                                                                                                                                 
loading packages...
resolving dependencies...
warning: cannot resolve "libappindicator-sharp", a dependency of "Todoist"
:: The following package cannot be upgraded due to unresolvable dependencies:
      Todoist

:: Do you want to skip the above package for this upgrade? [y/N] y
looking for conflicting packages...
 there is nothing to do
```
Even, the AUR pacakge is broken: https://aur.archlinux.org/packages/todoist-electron/ (for now) but editing that to remove `libappindicator-sharp` fixes the problem.

**Comment by KryDos** [comment]
hey @183amir,
Thanks for the report. I saw a comment in AUR too. 
I guess we can remove this dependency and make a new build. 
I wonder why is this package doesn't exist in the Arch repo anymore... 

I hope I can make a new build soon but any help is very appreciated in this.
