### ISSUE TITLE
Offer option to use Todoist Beta

### ISSUE THREAD

**Issue by ceiphr** [KryDos/todoist-linux#68]
Hi,
I love the project, but it would be nice if there was some setting that would allow me to switch to the beta web version of Todoist (https://beta.todoist.com) since that's what I am usually using.

**Comment by KryDos** [comment]
hi @ceiphr,
sounds like a good idea. 
I guess I can add that option to the configuration file. 

Feel free to send pull request if you'd like.

**Comment by KryDos** [comment]
Release is published here - https://github.com/KryDos/todoist-linux/releases/tag/1.20

It also includes your icons update. Thanks again!
