### ISSUE TITLE
add ability to refresh the content of the app

### ISSUE THREAD

**Issue by KryDos** [KryDos/todoist-linux#7]
sometimes it works not so good but refreshing fix everything. It would be great to have shortcut to refresh the content...

maybe it should be usual shortcut as it is in browser like "CTRL+R" or "CMD+R"

Ref - https://github.com/KryDos/todoist-linux/issues/3

**Comment by saikatm** [comment]
hey any updates?

**Comment by KryDos** [comment]
Nop :( it should be pretty easy to do but I'm still can't get to it. I suppose you can expect it somewhere at the weekend (end of this week).

**Comment by saikatm** [comment]
@KryDos thanks a lot. keep it up.

**Comment by KryDos** [comment]
Hey @saikatm thanks for the idea. The new 1.7 version has this shortcut added - https://github.com/KryDos/todoist-linux/releases/tag/1.7

You need to press `CTRL+ALT+r` when window is focused and the page should be refreshed.
