### ISSUE TITLE
Option to disable the tray icon

### ISSUE THREAD

**Issue by debevv** [KryDos/todoist-linux#74]
It would be nice to have to possibility to completely disable the tray icon with a config file option, and making the app terminate by clicking the "x" window button.
I find this more in line with the "Alt-Tab" workflow described in the repository readme, because the user will tend to keep the window application open all the time, making the space taken by the tray icon useless.
I tried to set the `tray-icon` to `null`, but i get a javascript exception

**Comment by KryDos** [comment]
hi @debevv,
thanks for the good idea. 

I made the change here - https://github.com/KryDos/todoist-linux/commit/38e2155d0bb2abbce3c0265b58c95b5bc401a5e3 but I'd like to collect a bit more changes to make new release. 

I can make a build specifically for you though. What system you're on?

**Comment by debevv** [comment]
Thanks!
I'm on Ubuntu 18.04 x86_64

**Comment by KryDos** [comment]
@debevv you can take deb package from [here](https://send.firefox.com/download/977468b65fa5c706/#-6a8OXq6kmRl5zYuBdwxLw)

**Comment by debevv** [comment]
The tray icon is not shown anymore, but i have two problems:
- When i close the app, the window disappears, but if i try to open it again i get the error in the picture. I noticed a Todoist process in the task manager still running, and i have to kill it to avoid the error  
![1](https://user-images.githubusercontent.com/8508972/79047060-b4a31c00-7c14-11ea-9714-e691334617d4.png)  
  

- When i minimize the window, i get this error  
![2](https://user-images.githubusercontent.com/8508972/79047071-c389ce80-7c14-11ea-8081-3fb42fc76409.png)

**Comment by KryDos** [comment]
Ah, it's good I didn't make a release, LOL. 

Sorry about that I didn't test it well enough. It's interesting that the process is not disappearing when you exit the program. I actually made the change to not keep the program running when "X" button is pressed. Interesting... 
I'll take a look

**Comment by debevv** [comment]
Yes, it is behaving very strangely. I wanted to add that when i minimize it, after the error I see two running processes in the task manager
