### ISSUE TITLE
Consider making this open source by adding a license

### ISSUE THREAD

**Issue by mbbroberg** [KryDos/todoist-linux#77]
Hey @KryDos, thanks so much for sharing this software with us. I'm a newer Linux user and able to get started thanks to awesome people like you sharing :smile:

I'm wondering if you'd be game to make this an officially open source project by adding a license reviewed by [the OSI](https://opensource.org/osd-annotated). Doing so is a great way to make the terms of usage clear and to provide your users with the freedom to fork, modify, and reproduce it legally. 

If you're looking for a quick review of options, check out https://choosealicense.com/licenses/. 

TL;DR MIT is a good default since it allows reuse with very few terms. GPL is great if you're passionate about [forks remaining open source as well](https://www.gnu.org/philosophy/free-sw.en.html).

**Comment by KryDos** [comment]
Good point. Thanks @mbbroberg!
 I'll take a look at what license I can use and probably you right, it's going to be MIT.

I'll let you know here when I chose a license.

**Comment by KryDos** [comment]
Added MIT license text to the repo. Thanks Matt!
