### ISSUE TITLE
WIll not open Ubuntu 20.04

### ISSUE THREAD

**Issue by netgifted** [KryDos/todoist-linux#79]
I removed and reinstalled 3 times. This worked fine for me on Ubuntu 19.10 but as I upgraded my system Todoist is not working anymore. The Window is blank and I have no way to refresh it. I didn't even get to login

**Comment by KryDos** [comment]
Wow. I'm sorry about that. 

I'll update my Ubuntu (I'm on 19.10 currently) and take a look what's going on. 

Thanks for the report @netgifted

**Comment by netgifted** [comment]
I’m actually running POP_OS 20.04
When I launched first time  it gave me an error message that I didn’t take note since it seamed a wrong login error. I don’t know if there is any cache that I can clean in order to get the same error message. I tried to uninstall multiple times with
sudo apt purge todoist
but it always opens as a blank window



Tony Silveira 
tony@netgifted.com

lestudio.tv
lestudionet.com

**Comment by KryDos** [comment]
Ah, thanks for letting me know about POP OS. It doesn't seems like distro specific issue. Maybe some library has been updated and todoist just won't work with that lib... Not sure yet. 

You can try to `rm -rf ~/.config/Todoist` where all the session/cookies/etc... is stored. I don't think this folder gets removed when `apt` command is used.

**Comment by laszukdawid** [comment]
I'm running on Ubuntu 20.04 and it's fine (though there's a slightly different problem, i.e. it's killed every few hours).

Have you seen any logs? Try searching through
```
$ journalctl -u snapd
```
