### ISSUE TITLE
external web links open in a new window instead of browser

### ISSUE THREAD

**Issue by saikatm** [KryDos/todoist-linux#8]
when clicking any link inside of the app the link opens in a new windows of the web wrapper instead of the default browser! here is a screenshot: 
![image](https://user-images.githubusercontent.com/9909763/39764421-352c276a-52fd-11e8-8a33-11c6c6195a30.png)

**Comment by KryDos** [comment]
brilliant catch! 

It should be fixed in 1.6 version. 

Sorry about such quick version bump, wasn't sure I will be able to fix it so quickly.

**Comment by saikatm** [comment]
Haha, you are on fire! Thanks for the fixes and sweet updates.
