### ISSUE TITLE
Is there an option so start minimized?

### ISSUE THREAD

**Issue by ielson** [KryDos/todoist-linux#81]
I'd like to start todoist in system startup, but it would be better if I could do start it minimized.
Is there some option that does it?

**Comment by KryDos** [comment]
hi @ielson,
unfortunately there is no way to do it right now but you're not the first person who ask about this. 

https://github.com/KryDos/todoist-linux/issues/43 - here is one more similar feature request. I'm closing this issue, please track the progress there.
