### ISSUE TITLE
Quick add shortcut key sequence

### ISSUE THREAD

**Issue by awmottaz** [KryDos/todoist-linux#83]
When I perform the following steps...

1. Open a project
2. Type `a` to append a task to the project
3. Close the window
4. Use the Quick Add shortcut

...then I will find myself in the append task text input with a "q" filled in the text input. Here's a screen recording of this sequence:

![Peek 2020-05-26 13-33](https://user-images.githubusercontent.com/17735385/82937317-95a6e200-9f55-11ea-8b2c-fcc9c0d30ec7.gif)

I am guessing that the Quick Add shortcut works by raising the app and then firing a keydown event with "q" to trigger the Todoist shortcut for quick add. If this is indeed the case, can this keydown sequence precede the "q" with a press of the Escape key? This way it closes whatever mode I left the app in and I get the Quick Input every time.

**Comment by KryDos** [comment]
hey @awmottaz, thanks for so good report and the gif. 

It works exactly as you mentioned. The qucik-add event opens the todoist window and then simulates `q` button press. I'll take a look if sending `esc`  key will help (it definitely should help). 

I'll let you know the result.

**Comment by awmottaz** [comment]
Thanks for the quick response @KryDos ! I just opened a PR to add the Escape keydown event. Hopefully that helps!
