### ISSUE TITLE
snap store version?

### ISSUE THREAD

**Issue by patrick330602** [KryDos/todoist-linux#85]
It would be great if this have a snap store version. and it is also super easy to get build a snap: https://snapcraft.io/docs/electron-apps

**Comment by Dude29** [comment]
There seems to be a version on the snap store already.
Check it out [here](https://snapcraft.io/todoist-thibaut)

**Comment by KryDos** [comment]
I'm having hard times supporting different stores/sources of the app. For example Arch's AUR repo is 2 version behind the latest release. 
I'm not mind to have snap version of the app but I don't think I will be good enough in supporting it. 

Do you guys know how to use continues integration (like CircleCI) solutions to automatically update AUR, Snap and possibly other sources? I researched this question for AUR recently and it should be doable fairly easily, I just have to spend some time on this but I honestly don't know if CircleCI can help with Snap store.

**Comment by diegolakatos** [comment]
> Do you guys know how to use continues integration (like CircleCI) solutions to automatically update AUR, Snap and possibly other sources? I researched this question for AUR recently and it should be doable fairly easily, I just have to spend some time on this but I honestly don't know if CircleCI can help with Snap store.

The CircleCI documentation has instructions on how to integrate with Snap store, I hope that this might be useful https://circleci.com/docs/2.0/build-publish-snap-packages/

**Comment by hellmrf** [comment]
The [Action Electron Builder](https://github.com/samuelmeuli/action-electron-builder) for Github Actions deploys to Snapcraft. Maybe it's useful.
