### ISSUE TITLE
In-app Todoist settings

### ISSUE THREAD

**Issue by tukusejssirs** [KryDos/todoist-linux#88]
Currently, the user can change settings in the browser only. Although there is a settings button, it simply opens the [Todoist website](https://todoist.com/prefs/account).

Would that be too much to grab the content and output it within the wrapper? :wink:

**Comment by KryDos** [comment]
hey @tukusejssirs, 
sounds like a good idea. Thanks! 
Feel free to send a PR, otherwise I'll take a look too.

**Comment by tukusejssirs** [comment]
@KryDos, I'll leave it for you, as I am don't develop front-end nor web(-app) stuff. 😉

**Comment by KryDos** [comment]
lol, sure :)

**Comment by Dude29** [comment]
@KryDos check out #93 and tell me what you think :smiley:
