### ISSUE TITLE
[Bug] window pop ups are not opening inside of the app

### ISSUE THREAD

**Issue by saikatm** [KryDos/todoist-linux#9]
The popups under todoist settings are not opening. please check. I am including a video.

![2018-05-16_13-38-41](https://user-images.githubusercontent.com/9909763/40104796-dffd5c6a-590e-11e8-9cfb-02b45fea99f4.gif)

**Comment by KryDos** [comment]
Interesting. Thanks a lot for the video. I guess the reason is the app included in iframe. As far as I know most of the google's services are forbit to include them in iframe. 

I'll check. Thanks a lot

**Comment by KryDos** [comment]
Hey @saikatm it should be fixed now. You can get it with new 1.7 version here - https://github.com/KryDos/todoist-linux/releases/tag/1.7

The issue happened since app is opening all links in external browser. But some of them obviously should be opened in the app itself.

**Comment by saikatm** [comment]
@KryDos oh my god! thank you so much! you are awesome. 👍
