### ISSUE TITLE
`make env` reformats the list of dependencies in `package.json`

### ISSUE THREAD

**Issue by tukusejssirs** [KryDos/todoist-linux#94]
This is a minor issue.

When I run `make env` (on Fedora 32 x86_64), it reformats the list of dependencies in `package.json` (see the diff bellow) and thus `git` marks it as modified file.

If you agree, I can create a PR to change the format, otherwise just close this issue.

<details>
<summary><code>git diff package.json</code></summary>

```bash
diff --git a/package.json b/package.json
index bf12f9f..19a9f81 100644
--- a/package.json
+++ b/package.json
@@ -19,7 +19,23 @@
             "category": "Utility;Productivity;"
         },
         "pacman": {
-            "depends": ["c-ares", "ffmpeg", "gtk3", "http-parser", "libevent", "libvpx", "libxslt", "libxss", "minizip", "nss", "re2", "snappy", "libnotify", "libappindicator-gtk2", "libappindicator-gtk3"]
+            "depends": [
+                "c-ares",
+                "ffmpeg",
+                "gtk3",
+                "http-parser",
+                "libevent",
+                "libvpx",
+                "libxslt",
+                "libxss",
+                "minizip",
+                "nss",
+                "re2",
+                "snappy",
+                "libnotify",
+                "libappindicator-gtk2",
+                "libappindicator-gtk3"
+            ]
         }
     },
     "devDependencies": {
</details>

**Comment by Dude29** [comment]
Happened to me aswell during development

**Comment by KryDos** [comment]
I wonder why `npm install` command would change the formatting... I didn't expect that and didn't see such issues in any projects I worked with. Probably because I never listed dependencies in one-line in those other projects. Good catch though

I just committed the reformatted version of package.json here - 124ec89
