### ISSUE TITLE
[Feature request] Quick add popup as separate window in any workspace

### ISSUE THREAD

**Issue by Oyveloper** [KryDos/todoist-linux#98]
Using the global shortcut for quick add works great whenever I am currently in the same workspace as I have my Todoist window, however if I'm on another workspace the popup will not show, since it is only displayed within the Todoist app. It would be awesome to have quick add as a global separate popup that would be visible in any workspace. This is how the official Todoist app works on macOS.

**Comment by KryDos** [comment]
hey @Oyveloper,
Yeah, I copmletely agree that it would be great but this todoist app is not a native one. Our "quick add" basically makes the Todoist window active and then virtually press "todoist's quick add keybinding" for you.

I'm pretty sure that is possible to implement a separate window that should appear on the screen when you want to quick add a task but I believe that window should be custom (implemented by us). 

Unfortunately I don't have time to do such work. I'll keep this issue open for others, maybe someone will implement this feature. 

Thanks for the great suggestion
