### ISSUE TITLE
Print not working

### ISSUE THREAD

**Issue by happydemic** [KryDos/todoist-linux#99]
Thanks for this great wrapper for Todoist - I use it every day. You've made the death of Wunderlist bearable.

I don't know anything about Electron, so sorry for the dumb question, but is there any way to make the Print option in the main menu work?

In a normal browser, selecting the Print option creates a new browser tab with the selected project in print format, and forces the Print dialogue. But at least for me (Ubuntu 18.04), the Electron wrapper closes those additional windows as soon as Todoist creates them, so it's not possible to print.

If that could be fixed it would be really helpful. Thanks again for your work on this.

**Comment by KryDos** [comment]
Thanks for kind words @happydemic 
Currently there is no way to print a page I believe. 

It seems like Electron has few methods/functions to print the content of a page but non of them is integrated with the app. I'll think about how to integrate that feature and let you know when it's done.

Obvously you can make it from the web version of Todoist but I understand that it would be much better to print a page from inside the app.
